```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
```

#### Plotting charts

```{r}
# The easiest way to get ggplot2 is to install the whole tidyverse
#install.packages("tidyverse")
#install.packages("ggplot2")
```


#### ggplot easy encapsulation through daltoolbox

```{r}
library(daltoolbox)
library(ggplot2)
```

#### Color Brewer R Package

```{r}
#install.packages("RColorBrewer")
library(RColorBrewer)
colors <- brewer.pal(4, 'Set1')
```


#### Basic setup for examples

Iris datasets

```{r}
head(iris, 3)
```

Options from graphics: colors and font size

```{r}
colors <- brewer.pal(4, 'Set1')
font <- theme(text = element_text(size=16))
```

#### Scatter plot


```{r fig.width=6, fig.height=4.5}
data <- data.frame(
  x = iris$Sepal.Length,
  value = iris$Sepal.Width,
  variable = iris$Species
)
#head(data)
grf <- plot_scatter(data, label_x = "Sepal.Length", label_y = "Sepal.Width", colors=colors[1:3]) + font
plot(grf)
```

#### Bar plot


```{r fig.width=6, fig.height=4.5}
agg <- aggregation("Species", Sepal.Length = mean(Sepal.Length))
data <- transform(agg, iris)
#head(data)
grf <- plot_bar(data, colors=colors[1:3]) + font
plot(grf)
```


#### Lollipop plot


```{r fig.width=6, fig.height=3.5}
agg <- aggregation("Species", Sepal.Length = mean(Sepal.Length))
data <- transform(agg, iris)
#head(data)
grf <- plot_lollipop(data, colors=colors[1], max_value_gap=0.2) + font + coord_flip() 
plot(grf)
```

#### Bar graph with error


```{r fig.width=6, fig.height=4.5}
agg <- aggregation("Species", mean = mean(Sepal.Length), sd = sd(Sepal.Length))
data <- transform(agg, iris)
#head(data)
grf <- plot_bar(data, colors=colors[1], alpha=1) + font
grf <- grf + geom_errorbar(data = data, inherit.aes = FALSE,
                           aes(x=Species, ymin=mean-sd, ymax=mean+sd), 
                           width=0.2, colour="darkred", alpha=0.8, size=1.1) 
plot(grf)
```



#### Pie plot


```{r fig.width=6, fig.height=4.5}
agg <- aggregation("Species", n = n())
data <- transform(agg, iris)
#head(data)
grf <- plot_pieplot(data, colors=colors[1:3]) + font
plot(grf)
```


#### Grouped bar


```{r fig.width=6, fig.height=4.5}
agg <- aggregation("Species",
  Sepal.Length = mean(Sepal.Length),
  Sepal.Width = mean(Sepal.Width)
)
data <- transform(agg, iris)

#head(data)
grf <- plot_groupedbar(data, colors=colors[1:2]) + font
plot(grf)
```


#### Stacked-bar


```{r fig.width=6, fig.height=4.5}
agg <- aggregation("Species",
  Sepal.Length = mean(Sepal.Length),
  Sepal.Width = mean(Sepal.Width)
)
data <- transform(agg, iris)

#head(data)
grf <- plot_stackedbar(data, colors=colors[1:2]) + font
grf <- grf + theme(axis.text.x = element_text(angle=90, hjust=1))
plot(grf)
```

#### Line chart


```{r fig.width=6, fig.height=4.5}
x <- seq(0, 10, 0.25)
serie <- data.frame(x, y=sin(x))

#head(serie)
grf <- plot_series(serie, colors=colors[1]) + font
plot(grf)
```

#### Data distribution example

```{r}
example <- data.frame(exponential = rexp(10000, rate = 1),
                      uniform = runif(10000, min=2.5, max = 3.5),
                      normal = rnorm(10000, mean = 5))
head(example)
```


```{r}

```

#### Histogram

```{r fig.width=6, fig.height=4.5}
data <- data.frame(exponential = example$exponential)
#head(data)
grf <- plot_hist(data, label_x = "exponential", color=colors[1]) + font
plot(grf) 
```


#### Multiple Histograms

```{r fig.width=12, fig.height=4.5}
{
library(gridExtra)  
grfe <- plot_hist(data.frame(exponential = example$exponential), label_x = "exponential", color=colors[1]) + font
grfu <- plot_hist(data.frame(uniform = example$uniform), label_x = "uniform", color=colors[1]) + font 
grfn <- plot_hist(data.frame(normal = example$normal), label_x = "normal", color=colors[1]) + font
grid.arrange(grfe, grfu, grfn, ncol=3)
}
```

#### Density plot


```{r fig.width=6, fig.height=4.5}
data <- data.frame(normal = example$normal)
#head(data)
grf <- plot_density(data, label_x = "normal", color=colors[1]) + font
plot(grf) 
```

#### Box plot


```{r fig.width=6, fig.height=4.5}
data <- data.frame(normal = example$normal)
#head(data)
grf <- plot_boxplot(data, colors="white") + font
plot(grf) 
```

